# Generated by Django 2.1 on 2019-03-23 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_year', models.IntegerField()),
                ('average_temperature', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('average_precipitation', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('source_text', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('longitude', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('event', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=3)),
                ('total_temperature', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_precipitation', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphs.GraphData')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyAverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=3)),
                ('ottawa_average_t', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('ottawa_average_p', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('victoria_average_t', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('victoria_average_p', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='YearlyAverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('ottawa_average_t', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('ottawa_average_p', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('victoria_average_t', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('victoria_average_p', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='graphdata',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphs.Student'),
        ),
    ]
