# Generated by Django 2.0 on 2019-03-10 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_year', models.IntegerField()),
                ('average_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('average_precipitation', models.DecimalField(decimal_places=2, max_digits=5)),
                ('source_text', models.CharField(max_length=50)),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('event', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='graphdata',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphs.Student'),
        ),
    ]
