# Generated by Django 2.0 on 2019-03-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphdata',
            name='event',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='graphdata',
            name='latitude',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='graphdata',
            name='longitude',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
