# Generated by Django 2.1 on 2019-03-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_auto_20190310_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphdata',
            name='average_precipitation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='graphdata',
            name='average_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='graphdata',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='graphdata',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='graphdata',
            name='source_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
