# Generated by Django 2.1 on 2019-03-23 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_auto_20190322_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthsGraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=3)),
                ('ottawa_average_t', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('ottawa_average_p', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('victoria_average_t', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('victoria_average_p', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='YearsGraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('ottawa_average_t', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('ottawa_average_p', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('victoria_average_t', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('victoria_average_p', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
            ],
        ),
    ]
