# Generated by Django 2.1 on 2019-03-19 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0004_auto_20190310_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=3)),
                ('total_temperature', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_precipitation', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphs.GraphData')),
            ],
        ),
    ]
