# Generated by Django 2.1 on 2019-03-19 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0005_monthdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonthData',
            new_name='Month',
        ),
    ]
