# Generated by Django 2.1 on 2019-03-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0006_auto_20190319_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphdata',
            name='latitude',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='graphdata',
            name='longitude',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
    ]
