# Generated by Django 2.1 on 2019-03-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0007_auto_20190319_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=3)),
                ('ottawa_average_t', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('ottawa_average_p', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('victoria_average_t', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('victoria_average_p', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='YearlyAverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('ottawa_average_t', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('ottawa_average_p', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('victoria_average_t', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('victoria_average_p', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
            ],
        ),
        migrations.AlterField(
            model_name='graphdata',
            name='average_precipitation',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='graphdata',
            name='average_temperature',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='graphdata',
            name='latitude',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='graphdata',
            name='longitude',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
